// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-LkI5Aa95Cty5g5q5gg3kmpYRN0bwRKQ',
    appId: '1:1086164648763:web:620785e74a1849df10ed1e',
    messagingSenderId: '1086164648763',
    projectId: 'saranotes',
    authDomain: 'saranotes-a3851.firebaseapp.com',
    storageBucket: 'saranotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABBAZ0Mt5O0RSXoCSme1zFwldIaV-fi34',
    appId: '1:1086164648763:android:d7550460d3a061d110ed1e',
    messagingSenderId: '1086164648763',
    projectId: 'saranotes',
    storageBucket: 'saranotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJfnNi6uxS8zKnfeNygSR_go3xJSrP1Fw',
    appId: '1:1086164648763:ios:e040bd8bc6764cfe10ed1e',
    messagingSenderId: '1086164648763',
    projectId: 'saranotes',
    storageBucket: 'saranotes.appspot.com',
    iosClientId: '1086164648763-42o0m5vpugohnuarnoqv4ehbjf4bd4fm.apps.googleusercontent.com',
    iosBundleId: 'sarawa.saranotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJfnNi6uxS8zKnfeNygSR_go3xJSrP1Fw',
    appId: '1:1086164648763:ios:e040bd8bc6764cfe10ed1e',
    messagingSenderId: '1086164648763',
    projectId: 'saranotes',
    storageBucket: 'saranotes.appspot.com',
    iosClientId: '1086164648763-42o0m5vpugohnuarnoqv4ehbjf4bd4fm.apps.googleusercontent.com',
    iosBundleId: 'sarawa.saranotes',
  );
}
